PerformanceTracker/Models/Group.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace PerformanceTracker.Models
{
    public partial class Group
    {
        public Group()
        {
            MessageTitles = new HashSet<MessageTitle>();
            Tasks = new HashSet<Task>();
            Owner = new User();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public int NumberOfMembers { get; set; }
        public DateTime ModifiedOn { get; set; }
        public int OwnerId { get; set; }
        public virtual User Owner { get; set; }
        public virtual ICollection<MessageTitle> MessageTitles { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}

PerformanceTracker/ViewModels/CreateGroup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PerformanceTracker.Models;

namespace PerformanceTracker.ViewModels
{
    public class CreateGroup
    {
        public CreateGroup()
        {
            Users = new List<User>();
        }
        public string Title { get; set;}
        public List<User> Users {get; set;}
        public List<int> SelectedUsersIds { get; set; }
    }
}

PerformanceTracker/Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
using PerformanceTracker.Models;
using PerformanceTracker.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace PerformanceTracker.Controllers
{
    public class GroupController : Controller
    {

        [HttpGet]
        public IActionResult GroupDetail(int groupId)
        {
            string sessionEmail = HttpContext.Session.GetString("useremail");
            if (sessionEmail != null)
            {
                GroupView groupModel = new GroupView();

                PerformanceTrackerContext db = new PerformanceTrackerContext();
                Models.Group detailedGroup = db.Groups.Include(x => x.MessageTitles)
                    .Include(x => x.Owner)
                    .Include(x => x.Tasks)
                    .FirstOrDefault(x => x.Id == groupId);
                if (detailedGroup != null)
                {
                    groupModel.Id = detailedGroup.Id;
                    groupModel.ownerId = detailedGroup.OwnerId;
                    groupModel.Title = detailedGroup.Title;
                    groupModel.NumberOfMembers = detailedGroup.NumberOfMembers;
                    groupModel.MessageTitles = detailedGroup.MessageTitles.ToList();
                    groupModel.Tasks = detailedGroup.Tasks.ToList();

                    List<Models.GroupMember> groupMembers = new List<Models.GroupMember>();
                    groupMembers = db.GroupMembers
                        .Include(x => x.User)
                                    .Include(x => x.Group)
                                    .Where(x => x.GroupId == detailedGroup.Id).ToList();

                    foreach (var gm in groupMembers)
                    {
                        groupModel.Members.Add(gm.User);
                    }
                    return View(groupModel);
                }
                else
                {
                    return RedirectToAction("CreateGroup", ViewBag.Error = "An error occured.");
                }
            }
            else
            {
                return RedirectToAction("Login", "Auth");
            }
        }
        [HttpPost]
        public IActionResult GroupDetail(ViewModels.GroupView posted)
        {
            string sessionEmail = HttpContext.Session.GetString("useremail");
            if (sessionEmail != null)
            {
                PerformanceTrackerContext db = new PerformanceTrackerContext();
                Models.Group detailedGroup = new Models.Group();
                detailedGroup = db.Groups.FirstOrDefault(g => g.Id == posted.Id);
                posted.Title = detailedGroup.Title;
                posted.MessageTitles = detailedGroup.MessageTitles.ToList();
                List<Models.GroupMember> groupMembers = new List<Models.GroupMember>();
                groupMembers = db.GroupMembers
                    .Include(x => x.User)
                    .Include(x => x.Group)
                    .Where(x => x.GroupId == detailedGroup.Id).ToList();
                foreach (var gm in groupMembers)
                {
                    posted.Members.Add(gm.User);
                }
                posted.NumberOfMembers = detailedGroup.NumberOfMembers;
                posted.Tasks = detailedGroup.Tasks.ToList();
                posted.Title = detailedGroup.Title;


                //if new message title is posted
                if (posted.NewMessageTitle != null)
                {
                    if (string.IsNullOrWhiteSpace(posted.NewMessageTitle.Title))
                    {
                        ViewBag.Error = "Message title must be filled.";
                    }
                    Models.MessageTitle newMT = new Models.MessageTitle();
                    newMT.Title = posted.NewMessageTitle.Title;
                    newMT.GroupId = posted.Id;
                    newMT.Group = db.Groups.FirstOrDefault(g => g.Id == posted.Id);
                    db.MessageTitles.Add(newMT);
                    db.SaveChanges();
                }
                if (posted.NewTask != null)
                {// if new task is posted
                    if (posted.NewTask.DueDate < DateTime.Now)
                    {
                        ViewBag.Error = "Please enter a valid due date.";
                        return RedirectToAction("GroupDetail", new { groupId = posted.Id });
                    }
                    if (string.IsNullOrWhiteSpace(posted.NewTask.Explanation) || string.IsNullOrWhiteSpace(posted.NewTask.Content))
                    {
                        ViewBag.Error = "All fields must be filled.";
                        return RedirectToAction("GroupDetail", new { groupId = posted.Id });
                    }

                    Models.Task newTask = new Models.Task();
                    newTask.Content = posted.NewTask.Content;
                    newTask.Explanation = posted.NewTask.Explanation;
                    newTask.GroupId = posted.Id;
                    newTask.Group = db.Groups.FirstOrDefault(g => g.Id == posted.Id);
                    newTask.StartDate = posted.NewTask.StartDate;
                    newTask.DueDate = posted.NewTask.DueDate;
                    newTask.ModifiedOn = DateTime.Now;
                    newTask.IsPublic = true;
                    db.Tasks.Add(newTask);
                    db.SaveChanges();
                    int newTaskId = newTask.Id;
                    // MODIFY TASK MEMBERS TABLE

                    foreach (int x in posted.SelectedMembersIds)
                    {
                        Models.TaskMember newMember = new Models.TaskMember();
                        newMember.UserId = x;
                        newMember.TaskId = newTaskId;
                        newMember.User = db.Users.FirstOrDefault(u => u.Id == x);
                        newMember.Task = newTask;
                        if (newTask.StartDate > DateTime.Now)
                        {
                            newMember.StatusId = 4; // not started
                        }
                        else
                        {
                            newMember.StatusId = 3; // ongoing
                        }
                        newMember.Status = db.Statuses.FirstOrDefault(s => s.Id == newMember.StatusId);
                        db.TaskMembers.Add(newMember);
                        db.SaveChanges();
                    }
                }
                return RedirectToAction("GroupDetail", new { groupId = posted.Id });
            }
            else
            {
                return RedirectToAction("Login", "Auth");
            }
        }
        [HttpGet]
        public IActionResult EditGroup(int groupId)
        {
            string sessionEmail = HttpContext.Session.GetString("useremail");
            if (sessionEmail != null)
            {
                EditGroupView editModel = new EditGroupView();
                PerformanceTrackerContext db = new PerformanceTrackerContext();
                Models.Group detailedGroup = db.Groups
                    .Include(x => x.Owner)
                    .FirstOrDefault(x => x.Id == groupId);
                editModel.Id = groupId;
                editModel.Title = detailedGroup.Title;
                List<Models.GroupMember> groupMembers = db.GroupMembers
                    .Include(gm => gm.User)
                    .Where(gm => gm.GroupId == groupId).ToList();
                foreach (var item in groupMembers)
                {
                    editModel.Members.Add(db.Users.FirstOrDefault(u => u.Id == item.UserId));
                }
                editModel.Others = db.Users.ToList();
                foreach (Models.User u in editModel.Members)
                {
                    editModel.Others.Remove(u);
                }
                editModel.Members.Remove(db.Users.FirstOrDefault(u => u.Id == detailedGroup.OwnerId));
                editModel.Others.Remove(db.Users.FirstOrDefault(u => u.Id == detailedGroup.OwnerId));
                return View(editModel);
            }
            else
            {
                return RedirectToAction("Login", "Auth");
            }
        }
        [HttpPost]
        public IActionResult EditGroup(ViewModels.EditGroupView posted)
        {
            string sessionEmail = HttpContext.Session.GetString("useremail");
            if (sessionEmail != null)
            {
                PerformanceTrackerContext db = new PerformanceTrackerContext();
                Models.Group currentGroup = db.Groups.FirstOrDefault(g => g.Id == posted.Id);
                if (posted.NewUsersIds != null && posted.NewUsersIds.Any())
                {//if new members are posted
                    foreach (int newId in posted.NewUsersIds)
                    {
                        Models.GroupMember newGM = new Models.GroupMember();
                        Models.User newUser = new Models.User();
                        newUser = db.Users.FirstOrDefault(u => u.Id == newId);
                        newGM.UserId = newId;
                        newGM.User = newUser;
                        newGM.GroupId = posted.Id;
                        newGM.Group = currentGroup;
                        db.GroupMembers.Add(newGM);
                        db.SaveChanges();
                    }
                    currentGroup.NumberOfMembers += posted.NewUsersIds.Count;
                    db.SaveChanges();
                }
                if (posted.DeletedUsersIds != null && posted.DeletedUsersIds.Any())
                {// if members are removed
                    foreach (int delId in posted.DeletedUsersIds)
                    {
                        Models.GroupMember deleteMember = db.GroupMembers
                            .FirstOrDefault(m => m.UserId == delId && m.GroupId == posted.Id);

PerformanceTracker/Controllers/MessageController.cs
using Microsoft.AspNetCore.Mvc;
using PerformanceTracker.Models;
using PerformanceTracker.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace PerformanceTracker.Controllers
{
    public class MessageController : Controller
    {
        [HttpGet]
        public IActionResult MessageBoard(int messageTitleId)
        {
            string sessionEmail = HttpContext.Session.GetString("useremail");
            if (sessionEmail != null)
            {
                PerformanceTrackerContext db = new PerformanceTrackerContext();
                ViewModels.MessageBoardView mbv = new MessageBoardView();
                mbv.MessageTitleId = messageTitleId;
                mbv.GroupId = db.MessageTitles.FirstOrDefault(mt => mt.Id == messageTitleId).GroupId;
                mbv.AllMessages.AddRange(db.Messages
                    .Include(m => m.User)
                    .Where(m => m.TitleId == messageTitleId)
                    .OrderBy(m => m.Time).ToList());
                mbv.Title = db.MessageTitles.FirstOrDefault(mt => mt.Id == messageTitleId).Title;
                return View(mbv);
            }
            else
            {
                return RedirectToAction("Login", "Auth");
            }
        }
        [HttpPost]
        public IActionResult SendMessage(MessageBoardView posted)
        {
            string sessionEmail = HttpContext.Session.GetString("useremail");
            if (sessionEmail != null)
            {
                PerformanceTrackerContext db = new PerformanceTrackerContext();
                if (!string.IsNullOrWhiteSpace(posted.NewMessage))
                {
                    Models.Message newMes = new Message();
                    newMes.Time = DateTime.Now;
                    newMes.Title = db.MessageTitles
                        .FirstOrDefault(mt => mt.Id == posted.MessageTitleId);
                    newMes.TitleId = posted.MessageTitleId;
                    User currentUser = db.Users
                        .FirstOrDefault(u => u.Email == sessionEmail);
                    newMes.User = currentUser;
                    newMes.UserId = currentUser.Id;
                    newMes.Content = posted.NewMessage;
                    db.Messages.Add(newMes);
                    db.SaveChanges();
                }
                return RedirectToAction("MessageBoard", new { messageTitleId = posted.MessageTitleId });
            }
            else
            {
                return RedirectToAction("Login", "Auth");
            }
        }
    }
}

PerformanceTracker/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using PerformanceTracker.Models;
using PerformanceTracker.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace PerformanceTracker.Controllers
{
    public class TaskController : Controller
    {
        [HttpGet]
        public IActionResult TaskDetail(int taskId)
        {
            string sessionEmail = HttpContext.Session.GetString("useremail");
            if (sessionEmail != null) // if user logged in
            {
                PerformanceTrackerContext db = new PerformanceTrackerContext();
                Models.Task detailedTask = db.Tasks
                    .Include(t => t.Group)
                    .FirstOrDefault(t => t.Id == taskId);
                ViewModels.TaskView tv = new TaskView();
                tv.Content = detailedTask.Content;
                tv.Explanation = detailedTask.Explanation;
                tv.DueDate = detailedTask.DueDate;
                tv.StartDate = detailedTask.StartDate;
                tv.GroupId = detailedTask.GroupId;
                tv.TaskId = taskId;
                tv.TaskMembers = db.TaskMembers
                    .Include(tm => tm.User)
                    .Include(tm => tm.Status)
                    .Where(tm => tm.TaskId == taskId).ToList();
                foreach (var item in tv.TaskMembers)
                {
                    if (item.Task.DueDate <= DateTime.Now)
                    {
                        item.StatusId = 2;
                    }
                    else if (item.Task.StartDate <= DateTime.Now && item.StatusId != 1)
                    {
                        item.StatusId = 3;
                    }
                    item.Status = db.Statuses.FirstOrDefault(s => s.Id == item.StatusId);
                    db.SaveChanges();
                }
                return View(tv);
            }
            else
            {
                return RedirectToAction("Login", "Auth");
            }
        }

        [HttpPost]
        public IActionResult CompleteTask(ViewModels.TaskView posted)
        {
            var sessionId = HttpContext.Session.GetInt32("userid");
            if (sessionId != null) // if user logged in
            {
                PerformanceTrackerContext db = new PerformanceTrackerContext();
                var taskMember = db.TaskMembers
                    .Include(tm => tm.Status)
                    .SingleOrDefault(tm => tm.TaskId == posted.TaskId && tm.UserId == sessionId);
                if (taskMember != null)
                {
                    taskMember.StatusId = 1;
                    taskMember.Status = db.Statuses.FirstOrDefault(s => s.Id == 1);
                    db.SaveChanges();
                }
                return RedirectToAction("TaskDetail", new { taskId = posted.TaskId });
            }
            else
            {
                return RedirectToAction("Login", "Auth");
            }
        }
    }
}

PerformanceTracker/Views/Group/CreateGroup.cshtml
@model PerformanceTracker.ViewModels.CreateGroup

@{
    ViewData["Title"] = "CreateGroup";
}

<h1>Create Group</h1>
<hr />

<div class="row">
    <form asp-action="CreateGroup" method="post">
        <div class="form-group">
            <label asp-for="Title" class="control-label"></label>
            <input required asp-for="Title" class="form-control" type="text" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <select class="form-select" multiple data-mdb-filter="true" asp-for="SelectedUsersIds">
                @foreach (var u in Model.Users)
                {
                    <option value="@u.Id">@u.FirstName @u.LastName - @u.Email</option>
                }
            </select>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" style="width:500px;" />
        </div>


        @if (ViewBag.Error != null)
        {
            <div class="alert alert-warning" role="alert">
                @ViewBag.Error
            </div>
        }
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PerformanceTracker/Views/Group/EditGroup.cshtml
@model PerformanceTracker.ViewModels.EditGroupView
@{
    ViewData["Title"] = "Edit Group";
}
<h1>@Model.Title</h1>
<hr />
<form asp-action="EditGroup" method="post">
    <input type="hidden" value="@Model.Id" name="Id" />
    <div class="row">
        <div class="form-group">
            <label asp-for="NewTitle" class="control-label">New Title</label>
            <input asp-for="NewTitle" class="form-control" type="text" style="width:100%; " />
            <span asp-validation-for="NewTitle" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="NewUsersIds" class="control-label">Add New Members</label>
                <select class="form-select" multiple data-mdb-filter="true" asp-for="NewUsersIds" style="width:100%; ">
                    @foreach (var u in Model.Others)
                    {
                        <option value="@u.Id">@u.FirstName @u.LastName - @u.Email</option>
                    }
                </select>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label asp-for="NewUsersIds" class="control-label">Remove Members</label>
                <select class="form-select" multiple data-mdb-filter="true" asp-for="DeletedUsersIds" style="width:100%; ">
                    @foreach (var u in Model.Members)
                    {
                        <option value="@u.Id">@u.FirstName @u.LastName - @u.Email</option>
                    }
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <input type="submit" value="Edit" class="btn btn-primary" style="width:100%;" />
        </div>
    </div>


    @if (ViewBag.Error != null)
    {
        <div class="alert alert-warning" role="alert">
            @ViewBag.Error
        </div>
    }
</form>

PerformanceTracker/Views/Group/GroupDetail.cshtml
@model PerformanceTracker.ViewModels.GroupView
@using Microsoft.AspNetCore.Http;

@{
    ViewData["Title"] = "Group";
}

<h1>@Model.Title</h1>
<div class="col-sm-10">
    @Html.DisplayFor(model => model.NumberOfMembers) members
</div>
<hr />

<div>
    <div class="row">
        <div class="col">
            <h5>Tasks</h5>
            @*list current tasks*@
            @foreach (var t in Model.Tasks)
            {
                @Html.ActionLink(t.Content, "TaskDetail", "Task",
                 new { taskId = t.Id }, // giving parameter to IActionResult function
                 new { @class = "list-group-item list-group-item-action" })//html attribute
            }
            @*create new task*@
            @if (Context.Session.GetInt32("userid") == Model.ownerId)
            {
                <input type="button" name="answer" value="New Task" onclick="newTask()" class="btn btn-primary" />
                <form id="add_new_task" asp-action="GroupDetail" method="post" style="display: none">
                    <input type="hidden" value="@Model.Id" name="Id" />
                    <div class="form-group">
                        <label asp-for="NewTask.Content" class="control-label">Title</label>
                        <input required asp-for="NewTask.Content" class="form-control" type="text" />
                        <span asp-validation-for="NewTask.Content" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="NewTask.Explanation" class="control-label">Explanation</label>
                        <textarea required asp-for="NewTask.Explanation" class="form-control" type="text" rows="5">Explanation</textarea>
                        <span asp-validation-for="NewTask.Explanation" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="SelectedMembersIds" class="control-label">Select Members</label>
                        <select asp-for="SelectedMembersIds" class="form-select" multiple data-mdb-filter="true" style="width:100%; required">
                            @foreach (var u in Model.Members)
                            {
                                <option value="@u.Id">@u.FirstName @u.LastName - @u.Email</option>
                            }
                        </select>
                    </div>

                    @*is public için select all yapan check box konulacak ve otomatik olarak listedeki herkesi seçecek*@
                    <div class="form-group">
                        <label asp-for="NewTask.StartDate" class="control-label">Start Date</label>
                        <input class="form-control" asp-for="NewTask.StartDate" />
                        <span asp-validation-for="NewTask.StartDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="NewTask.DueDate" class="control-label">Due Date</label>
                        <input class="form-control" asp-for="NewTask.DueDate" />
                        <span asp-validation-for="NewTask.DueDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            }
        </div>

        <div class="col">
            <h5>Message Titles</h5>

            @*list current message titles*@
            @foreach (var m in Model.MessageTitles)
            {
                @Html.ActionLink(m.Title, "MessageBoard", "Message",
                 new { messageTitleId = m.Id }, // giving parameter to IActionResult function
                 new { @class = "list-group-item list-group-item-action" })//html attribute
            }
            @*create new message title*@
            <input type="button" name="answer" value="New Message Title" onclick="newMessageTitle()" class="btn btn-primary" />
            <form id="add_new_message_title" asp-action="GroupDetail" method="post" style="display: none">
                <input type="hidden" value="@Model.Id" name="Id" />
                <div class="form-group">
                    <label asp-for="NewMessageTitle.Title" class="control-label">Title</label>
                    <input required asp-for="NewMessageTitle.Title" class="form-control" type="text" />
                    <span asp-validation-for="NewMessageTitle.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>
@if (Context.Session.GetInt32("userid") == Model.ownerId)
{
    <div class="row">
        @Html.ActionLink("Edit Group", "EditGroup", "Group",
               new { groupId = Model.Id }, // giving parameter to IActionResult function
             null)
    </div>
    <div class="row">
        <form asp-action="DeleteGroup" method="post">
            <input type="hidden" value="@Model.Id" name="Id" />
            <button type="submit" class="btn btn-danger">Delete Group</button>
        </form>
    </div>
}
@if (ViewBag.Error != null)
{
    <div class="alert alert-warning row" role="alert" style="width: 100%">
        @ViewBag.Error
    </div>
}


<script>
    function newTask() {
        if (document.getElementById("add_new_task").style.display == "none") {
            document.getElementById("add_new_task").style.display = "block";
        } else if (
            document.getElementById("add_new_task").style.display == "block"
        ) {
            document.getElementById("add_new_task").style.display = "none";
        }
    }

    function newMessageTitle() {
        if (document.getElementById("add_new_message_title").style.display == "none") {
            document.getElementById("add_new_message_title").style.display = "block";
        } else if (
            document.getElementById("add_new_message_title").style.display == "block"
        ) {
            document.getElementById("add_new_message_title").style.display = "none";
        }
    }
</script>